apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-homelab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/galavernag/k8s-homelab
    targetRevision: HEAD
    path: apps/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
